[package]
name = "cccgt"
version = "0.1.0"
authors = ["Andrew Jones <ascjones@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.0"
clap = { version = "~2.32", features = ["yaml"] }
steel-cent = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.2.0"
csv = "1.0.5"
prettytable-rs = "^0.8"
derive_more = "0.15.0"
log = "0.4.8"
pretty_env_logger = "0.3.1"
