[package]
name = "cccgt"
version = "0.1.0"
authors = ["Andrew Jones <ascjones@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
rusty-money = { git = "https://github.com/varunsrin/rusty_money" }
serde = { version = "1.0.118", features = ["derive"] }
lazy_static = "1.4.0"
csv = "1.1.5"
prettytable-rs = "0.8.0"
derive_more = "0.99.11"
log = "0.4.11"
pretty_env_logger = "0.4.0"
argh = "0.1.4"
ureq = { version = "2.0.1", features = ["json"] }
color-eyre = "0.5.10"
rust_decimal = { version = "1.9.0", features = ["serde"] }
rust_decimal_macros = "1.10.1"
hex = "0.4.2"
hmac = "0.10.1"
sha2 = "0.9.2"
url = "2.2.0"
